SELECT DATE(NOW());
SELECT DATE(created_time) FROM t_item;
USE db3;
SHOW databases;
USE db3;
SELECT EXTRACT(YEAR FROM hiredate) FROM emp;
SELECT NOW();
SELECT DATE_FORMAT(NOW(),'%Y年%m月%d日 %H时%i分%s秒');
SELECT DATE_FORMAT(created_time,'%Y年%m月%d日 %H时%i分%s秒') FROM t_item;
select str_to_date('25号12月2015年','%d号%m月%Y');
update emp set comm=ifnull(comm,0);
select*from emp;
select ename,concat(sal,'元')from emp;
select ename,char_length(ename)from emp;
select instr('nba','a');
select locate('a','nba');
select insert('abcdefg',3,3,'m');
select upper('nBa');
select replace('abcdefg','a','bb');
select repeat('aa',2);
select floor(3.75);
select round(3.2837,2);
select floor(rand()*6); 